//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultPage.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getData", ReplyAction="http://tempuri.org/IService1/getDataResponse")]
        string getData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getData", ReplyAction="http://tempuri.org/IService1/getDataResponse")]
        System.Threading.Tasks.Task<string> getDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockBuild", ReplyAction="http://tempuri.org/IService1/StockBuildResponse")]
        void StockBuild(int numOfStocks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockBuild", ReplyAction="http://tempuri.org/IService1/StockBuildResponse")]
        System.Threading.Tasks.Task StockBuildAsync(int numOfStocks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockQuote", ReplyAction="http://tempuri.org/IService1/StockQuoteResponse")]
        double StockQuote(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockQuote", ReplyAction="http://tempuri.org/IService1/StockQuoteResponse")]
        System.Threading.Tasks.Task<double> StockQuoteAsync(string symbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DefaultPage.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DefaultPage.ServiceReference1.IService1>, DefaultPage.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getData() {
            return base.Channel.getData();
        }
        
        public System.Threading.Tasks.Task<string> getDataAsync() {
            return base.Channel.getDataAsync();
        }
        
        public void StockBuild(int numOfStocks) {
            base.Channel.StockBuild(numOfStocks);
        }
        
        public System.Threading.Tasks.Task StockBuildAsync(int numOfStocks) {
            return base.Channel.StockBuildAsync(numOfStocks);
        }
        
        public double StockQuote(string symbol) {
            return base.Channel.StockQuote(symbol);
        }
        
        public System.Threading.Tasks.Task<double> StockQuoteAsync(string symbol) {
            return base.Channel.StockQuoteAsync(symbol);
        }
    }
}
